spring:
  cloud:
    config:
      uri: http://127.0.0.1:5500/
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: nexus
eureka:
  instance:
    hostname: 127.0.0.1
    instanceId: ${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/